export const FETCH_SALES_REPORT_REQUEST = 'FETCH_SALES_REPORT_REQUEST';
export const FETCH_SALES_REPORT_SUCCESS = 'FETCH_SALES_REPORT_SUCCESS';
export const FETCH_SALES_REPORT_FAIL = 'FETCH_SALES_REPORT_FAIL';
export const SET_DATE_RANGE = 'SET_DATE_RANGE';